apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme-app"
spec:
  selector:
    matchLabels:
      app: "app-acme"
  replicas: 5
  template:
    metadata:
      labels:
        app: "app-acme"
    spec:
      containers:
      - image: ~/src/Dockerfile
        imagePullPolicy: Always
        name: "app-acme"
        ports:
        - containerPort: 80