apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app"
spec:
  selector:
    matchlabel:
      app: "rmit-app"
  replicas: 5
  template:
    metadata:
      labels:
        app: "rmit-app"
    specs:
      contianers:
        - image: ~/src/Dockerfile
          imagePullPolicy: Always
          name: "rmit-app"
          ports:
          - contianerPort: 80